// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiFKkCnrdGRxjfrD8FdjFqDc0vWZUpTqs',
    appId: '1:980555481103:web:bd4940f92089fee02ae37a',
    messagingSenderId: '980555481103',
    projectId: 'flutter-pos-1f47a',
    authDomain: 'flutter-pos-1f47a.firebaseapp.com',
    storageBucket: 'flutter-pos-1f47a.appspot.com',
    measurementId: 'G-C24SHXMXQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfP50kcLFhzj5TwHrop6BzNkUCTPxk8d0',
    appId: '1:980555481103:android:58330cf7b389ee842ae37a',
    messagingSenderId: '980555481103',
    projectId: 'flutter-pos-1f47a',
    storageBucket: 'flutter-pos-1f47a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlOHF9JBJlfm4PC-DVSVVM8k2YsiHqxOQ',
    appId: '1:980555481103:ios:f28df2e45cd215a42ae37a',
    messagingSenderId: '980555481103',
    projectId: 'flutter-pos-1f47a',
    storageBucket: 'flutter-pos-1f47a.appspot.com',
    iosBundleId: 'com.example.flutterPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlOHF9JBJlfm4PC-DVSVVM8k2YsiHqxOQ',
    appId: '1:980555481103:ios:f28df2e45cd215a42ae37a',
    messagingSenderId: '980555481103',
    projectId: 'flutter-pos-1f47a',
    storageBucket: 'flutter-pos-1f47a.appspot.com',
    iosBundleId: 'com.example.flutterPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiFKkCnrdGRxjfrD8FdjFqDc0vWZUpTqs',
    appId: '1:980555481103:web:b634158b7e2abb902ae37a',
    messagingSenderId: '980555481103',
    projectId: 'flutter-pos-1f47a',
    authDomain: 'flutter-pos-1f47a.firebaseapp.com',
    storageBucket: 'flutter-pos-1f47a.appspot.com',
    measurementId: 'G-XZ4ZX2S7Y7',
  );
}
